# Generated by Django 4.1.1 on 2022-09-18 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirlineAgentProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline_agent_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        default="", max_length=75, verbose_name="Position"
                    ),
                ),
                (
                    "user_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/users/profiles/%Y/%m/%d/",
                        verbose_name="User Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProvisorProfile",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="profiles.profile",
                    ),
                ),
                ("provisor_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("profiles.profile",),
        ),
    ]
