# Generated by Django 3.1.7 on 2022-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='uploads/users/profiles/qr/%Y/%m/%d', verbose_name='QR'),
        ),
    ]
