# Generated by Django 4.1.1 on 2022-09-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
        ("orders", "0003_remove_order_agent_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.agent",
            ),
        ),
    ]
