# Generated by Django 4.1.1 on 2022-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
        ("orders", "0004_order_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="agent",
        ),
        migrations.AddField(
            model_name="order",
            name="agent",
            field=models.ManyToManyField(to="agents.agent"),
        ),
    ]
