# Generated by Django 3.1.7 on 2022-09-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('AOG', 'Aog service'), ('BLS', 'Ballast handling'), ('TRA', 'Transport, loading service'), ('NEW', 'New request')], default='NEW', max_length=3)),
                ('title', models.CharField(max_length=155)),
                ('body', models.TextField()),
                ('service_date', models.DateTimeField(blank=True)),
                ('request_status', models.CharField(choices=[('draft', 'Draft'), ('send', 'Send')], default='draft', max_length=10)),
                ('creatAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
            options={
                'ordering': ('-service_date',),
            },
        ),
    ]
