# Generated by Django 4.1.1 on 2022-09-18 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyPerson",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="Full Name"),
                ),
                (
                    "position",
                    models.CharField(max_length=50, verbose_name="Person position"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=12, verbose_name="Contact Phone"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AogService",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_createAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="DateTime created"
                    ),
                ),
                (
                    "data_updateAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="DateTime updated"
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Service date")),
                ("service_time", models.TimeField(verbose_name="Service time")),
                (
                    "service_name",
                    models.CharField(max_length=50, verbose_name="Service name"),
                ),
                (
                    "aog_type",
                    models.CharField(
                        choices=[("loading", "Loading"), ("offloading", "Offloading")],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("flight", models.CharField(max_length=7, verbose_name="Flight")),
                (
                    "flight_ac_reg",
                    models.CharField(
                        default="", max_length=8, verbose_name="AC Registration"
                    ),
                ),
                (
                    "flight_date",
                    models.DateField(blank=True, null=True, verbose_name="Flight date"),
                ),
                (
                    "flight_time",
                    models.TimeField(blank=True, null=True, verbose_name="Flight time"),
                ),
                ("fix_required", models.BooleanField(default=False)),
                ("starps_count", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_services_request",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
