# Generated by Django 3.1.7 on 2022-09-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AogService',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_createAt', models.DateTimeField(auto_now=True, verbose_name='DateTime created')),
                ('data_updateAt', models.DateTimeField(auto_now_add=True, verbose_name='DateTime updated')),
                ('service_date', models.DateField(verbose_name='Service date')),
                ('service_time', models.TimeField(verbose_name='Service time')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service name')),
                ('aog_type', models.CharField(choices=[('loading', 'Loading'), ('offloading', 'Offloading')], max_length=50, verbose_name='Type')),
                ('flight', models.CharField(max_length=7, verbose_name='Flight')),
                ('flight_ac_reg', models.CharField(default='', max_length=8, verbose_name='AC Registration')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Flight date')),
                ('flight_time', models.TimeField(blank=True, null=True, verbose_name='Flight time')),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_service_request', to='agents.agent')),
                ('aog_item', models.ManyToManyField(to='stuffs.Aog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
