# Generated by Django 3.1.7 on 2022-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aogservice',
            name='fix_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='starps_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
