# Generated by Django 4.1.1 on 2022-09-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aogservice',
            name='aog_type',
        ),
        migrations.AlterField(
            model_name='aogservice',
            name='service_name',
            field=models.CharField(choices=[('loading', 'Loading Wheels'), ('offloading', 'Unloading Wheels')], max_length=50, verbose_name='Service Name'),
        ),
    ]
