# Generated by Django 3.1.7 on 2022-09-10 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_user'),
        ('services', '0002_auto_20220910_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyPerson',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='Responsible person')),
                ('position', models.CharField(max_length=50, verbose_name='Person position')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='Contact Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aogservice',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_services_request', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='aogservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='responsibles_persons',
            field=models.ManyToManyField(to='services.DutyPerson'),
        ),
    ]
