# Generated by Django 3.1.7 on 2022-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220910_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyperson',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
    ]
