# Generated by Django 4.1.1 on 2022-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/agents/icons/%Y/%m/%d/",
                        verbose_name="Agent Icon",
                    ),
                ),
            ],
        ),
    ]
