# Generated by Django 4.1.1 on 2022-09-18 11:50

from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcEngine",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "item_weight",
                    django_measurement.models.MeasurementField(
                        default=0, measurement=measurement.measures.mass.Mass
                    ),
                ),
                (
                    "item_serial_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Serial number",
                    ),
                ),
                (
                    "item_part_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Part number"
                    ),
                ),
                (
                    "item_lenght",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_width",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_height",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "image_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/stuffs/engins"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AcStand",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "item_weight",
                    django_measurement.models.MeasurementField(
                        default=0, measurement=measurement.measures.mass.Mass
                    ),
                ),
                (
                    "item_serial_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Serial number",
                    ),
                ),
                (
                    "item_part_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Part number"
                    ),
                ),
                (
                    "item_lenght",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_width",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_height",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "image_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/stuffs/stands"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aog",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "item_weight",
                    django_measurement.models.MeasurementField(
                        default=0, measurement=measurement.measures.mass.Mass
                    ),
                ),
                (
                    "item_lenght",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_width",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_height",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "image_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/stuffs/aog"
                    ),
                ),
                (
                    "item_part_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Part number"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAog",
            fields=[
                (
                    "pkid",
                    models.BigIntegerField(blank=True, db_index=True, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "item_weight",
                    django_measurement.models.MeasurementField(
                        default=0, measurement=measurement.measures.mass.Mass
                    ),
                ),
                (
                    "item_lenght",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_width",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_height",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "image_document",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "item_part_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Part number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aog",
                "verbose_name_plural": "historical aogs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "item_weight",
                    django_measurement.models.MeasurementField(
                        default=0, measurement=measurement.measures.mass.Mass
                    ),
                ),
                (
                    "item_serial_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Serial number",
                    ),
                ),
                (
                    "item_part_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Part number"
                    ),
                ),
                (
                    "item_lenght",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_width",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "item_height",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.distance.Distance,
                        null=True,
                    ),
                ),
                (
                    "image_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/stuffs/instr"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
