# Generated by Django 3.1.7 on 2022-09-09 10:13

from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcEngine',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_height', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/engins')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcStand',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_height', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/stands')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aog',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('item_lenght', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_height', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/aog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('item_height', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True)),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/instr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
