# Generated by Django 3.1.7 on 2022-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aog',
            name='item_part_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number'),
        ),
    ]
