# Generated by Django 3.1.7 on 2022-09-10 08:17

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_aog_item_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acengine',
            name='item_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
        migrations.AlterField(
            model_name='acstand',
            name='item_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
        migrations.AlterField(
            model_name='aog',
            name='item_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='item_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
    ]
