# Generated by Django 4.1.1 on 2022-09-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='', max_length=65, verbose_name='Country'),
        ),
    ]
